- name: php-fpm restart
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: php-fpm start
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: php-fpm stop
  service:
    name: php-fpm
    state: stopped
