all:
  children:
    local:
      hosts:
        test-vm01:
          ansible_host: 192.168.10.20
        test-vm02:
          ansible_host: 192.168.10.22
      children: 
        nginx:
          hosts:
            test-vm01:
        php_fpm:
          hosts:
            test-vm02: